services:
  prometheus:
    image: prom/prometheus:latest
    container_name: mediatek_prometheus
    volumes:
      - ./docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - mediatek_net

  grafana:
    image: grafana/grafana:latest
    container_name: mediatek_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - mediatek_net
    depends_on:
      - prometheus
      - loki

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: mediatek_cadvisor
    privileged: true
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - mediatek_net

  loki:
    image: grafana/loki:latest
    container_name: mediatek_loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./docker/monitoring/loki/loki-config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki
    networks:
      - mediatek_net

  promtail:
    image: grafana/promtail:latest
    container_name: mediatek_promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./docker/monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mediatek_net
    depends_on:
      - loki

volumes:
  grafana_data:
  prometheus_data:
  loki_data:

networks:
  mediatek_net:
    external: true
    name: mediatek_net