{
 "title": "App logs",
 "tags": [
  "loki",
  "logs",
  "symfony",
  "docker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "compose_service", "label": "Compose service", "query": "label_values(compose_service)" },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values({compose_service=~\"$compose_service\"}, container)"
   },
   { "name": "search", "label": "Search (regex)", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "App logs (Loki)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "PHP logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{compose_service=\"php\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Logs (service sélectionné)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{compose_service=~\"$compose_service\", container=~\"$container\"} |~ \"$search\""
    }
   ]
  }
 ]
}